//
//  DetailMoviePresenter.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation

protocol DetailMoviePresenterLogic: BasePresenterLogic {
    func presentDetailMovie(entity: DetailMovieEntity)
    func presentReview(entities: [ReviewEntity])
    func presentTrailer(entities: [TrailerEntity])
}

class DetailMoviePresenter: DetailMoviePresenterLogic {
    
    weak var viewController: DetailMovieDisplayLogic?
    
    func presentDetailMovie(entity: DetailMovieEntity) {
        let viewModel = DetailMovieViewModel.init(entity: entity)
        viewController?.displayDetailMovie(viewModel: viewModel)
    }
    
    func presentAlert(with message: String) {
        viewController?.displayAlert(with: message)
    }
    
    func presentReview(entities: [ReviewEntity]) {
        let viewModels = entities.map(ReviewViewModel.init)
        viewController?.displayReview(viewModels: viewModels)
    }
    
    func presentTrailer(entities: [TrailerEntity]) {
        let viewModels = entities.map(TrailerViewModel.init)
        viewController?.displayTrailer(viewModels: viewModels)
    }
}

class DetailMovieViewModel{
    
    private let entity: DetailMovieEntity
    
    init(entity: DetailMovieEntity) {
        self.entity = entity
    }
    
    var getEntity: DetailMovieEntity {
        return entity
    }
    
    var id: Int {
        return entity.id
    }
    
    var title: String {
        return entity.title
    }
    
    var description: String {
        return entity.description
    }
}

class ReviewViewModel {
    
    private let entity: ReviewEntity
    
    init(entity: ReviewEntity) {
        self.entity = entity
    }
    
}


class TrailerViewModel {
    
    private let entity: TrailerEntity
    
    init(entity: TrailerEntity) {
        self.entity = entity
    }
}
