//
//  ReviewRepositoryImpl.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

class ReviewRepositoryImpl: ReviewRepositoryLogic {
    
    private let datasource: ReviewRemoteDataSource
    
    init(datasource: ReviewRemoteDataSource) {
        self.datasource = datasource
    }
    
    func getReview(parameter: [String : Any],
                   completion: @escaping (Result<[ReviewEntity], DataError>) -> Void) {
        
        datasource.fetchReview(param: parameter) { result in
            switch result {
            case .failure(let error):
                completion(.failure(error))
            case .success(let models):
                let entities = models.map {
                    ReviewEntity(author: $0.author ?? "",
                                 username: $0.authorDetails?.username ?? "",
                                 avatar: $0.authorDetails?.avatarPath ?? "",
                                 content: $0.content ?? "",
                                 rating: $0.authorDetails?.rating ?? 0)
                }
                completion(.success(entities))
            }
        }
    }
}
