//
//  DetailMovieRemoteDataSource.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

protocol DetailMovieRemoteDataSource {
    
    func fetchDetailMovie(param: [String: Any],
                       completion: @escaping(Result<InformationResponse, DataError>) -> Void)
    
    func fetchReview(param: [String: Any],
                     completion: @escaping(Result<[ReviewModel], DataError>) -> Void)
    
    func fetchTrailer(param: [String: Any],
                     completion: @escaping(Result<[TrailerModel], DataError>) -> Void)
}

class DetailMovieRemoteDataSourceImpl: DetailMovieRemoteDataSource{
    
    func fetchDetailMovie(param: [String : Any],
                       completion: @escaping (Result<InformationResponse, DataError>) -> Void) {
    
        guard let id = param["id"] as? Int else {
            completion(.failure(.init(errorState: .undefinedError)))
            return }
        
        var query: [String: Any] = [:]
        for (key, value) in param where key != "id" {
            query[key] = value
        }
        
        let endpoint = "/movie/\(id)"
        NetworkManager.shared.request(with: endpoint, withParameter: query) { (result) in
            switch result {
            case let .failure(error):
                completion(.failure(error))
                break
            case let .success(data):
                do {
                    let json = try JSONDecoder().decode(InformationResponse.self, from: data)
                    completion(.success(json))
                } catch {
                    completion(.failure(.init(errorState: .parseError)))
                }
            }
        }
        
    }
    
    func fetchReview(param: [String : Any], completion: @escaping (Result<[ReviewModel], DataError>) -> Void) {
       
        guard let id = param["id"] as? Int else {
            completion(.failure(.init(errorState: .undefinedError)))
            return }
        
        var query: [String: Any] = [:]
        for (key, value) in param where key != "id" {
            query[key] = value
        }
        
        let endpoint = "/movie/\(id)/reviews"
        NetworkManager.shared.request(with: endpoint, withParameter: query) { (result) in
            switch result {
            case let .failure(error):
                completion(.failure(error))
            case let .success(data):
                do {
                   let json = try JSONDecoder().decode(ReviewResponse.self, from: data)
                    completion(.success(json.results ?? []))
                } catch  {
                    completion(.failure(.init(errorState: .parseError)))
                }
            }
        }
    }
    
    func fetchTrailer(param: [String : Any], completion: @escaping (Result<[TrailerModel], DataError>) -> Void) {
        
        guard let id = param["id"] as? Int else {
            completion(.failure(.init(errorState: .undefinedError)))
            return }
        
        var query: [String: Any] = [:]
        for (key, value) in param where key != "id" {
            query[key] = value
        }
        
        let endpoint = "/movie/\(id)/videos"
        NetworkManager.shared.request(with: endpoint, withParameter: query) { (result) in
            switch result {
            case let .failure(error):
                completion(.failure(error))
                break
            case let .success(data):
                do {
                    let json = try JSONDecoder().decode(TrailerResponse.self, from: data)
                    completion(.success(json.results ?? []))
                } catch  {
                    completion(.failure(.init(errorState: .parseError)))
                }
                break
            }
        }
    }
    
}
