//
//  GenreRepositoryLogic.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

protocol GenreRepositoryLogic {
    func getGenre(parameter: [String: Any],
                             completion: @escaping(Result<[GenreEntity], DataError>) -> Void)
}

