//
//  GenreRouter.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation
import UIKit

protocol GenreRouterLogic {
    func navigateToDiscover(with item: GenreEntity)
}

class GenreRouter: GenreRouterLogic {
    
    weak var viewController: GenreUI?
    
    func navigateToDiscover(with item: GenreEntity) {
        let destination = viewController?.storyboardInstanceWithID(name: "Main", identifier: "DiscoverVC") as! DiscoverUI
        destination.state.titleName = item.name
        destination.state.genreId = item.id
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
}
