//
//  DetailMovieUI.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation
import UIKit

protocol DetailMovieDisplayLogic: BaseDisplayLogic{
    func displayDetailMovie(viewModel: DetailMovieViewModel)
    func displayReview(viewModels: [ReviewViewModel])
    func displayTrailer(viewModels: [TrailerViewModel])
}

class DetailMovieUI: BaseViewController{
    
    //dependency
    var interactor: DetailMovieInteractorLogic?
    var router: DetailMovieRouterLogic?
    
    //state
    let state = DetailMovieUIState()
    
    init() {
        super.init(nibName: nil, bundle: nil)
        DetailMovieConfigurator.inject(dependencyFor: self)
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        DetailMovieConfigurator.inject(dependencyFor: self)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.controllerName = "\(DetailMovieUI.self)"
        
        self.view.backgroundColor = .white
        
        let param = DetailMovieRequest(id: state.id)
        interactor?.getDetailMovie(param: param)
        
        let reviewParam = ReviewRequest(id: state.id)
        interactor?.getReview(param: reviewParam)
        
        let trailerParam = TrailerRequest(id: state.id)
        interactor?.getTrialer(param: trailerParam)
    }
    
}
