//
//  DiscoverRouter.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation
import UIKit

protocol DiscoverRouterLogic {
    func navigateToDetailMovie(with item: DiscoverEntity)
}

class DiscoverRouter: DiscoverRouterLogic {
    
    weak var viewController: DiscoverUI?
    
    func navigateToDetailMovie(with item: DiscoverEntity) {
        let destination = viewController?
            .storyboardInstanceWithID(name: "Main",
                                      identifier: "detail_movie_ui") as! DetailMovieUI
        destination.state.id = item.id
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
}
