//
//  GenreModel.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

struct GenreResponse: Codable {
    let genres: [GenreModel]
}

struct GenreModel: Codable{
    
    let id: Int?
    let name: String?
    
    enum CodingKeys: String, CodingKey{
        case id = "id"
        case name = "name"
    }

}
