//
//  DiscoverPresenter.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation

protocol DiscoverPresenterLogic: BasePresenterLogic {
    func presentDiscover(entities: [DiscoverEntity])
    func presentMoreDiscover(entities: [DiscoverEntity])
}

class DiscoverPresenter: DiscoverPresenterLogic {
    
    weak var viewController: DiscoverDisplayLogic?
    
    func presentDiscover(entities: [DiscoverEntity]) {
        let viewModels = entities.map(DiscoverViewModel.init)
        viewController?.displayDiscover(viewModels: viewModels)
    }
    
    func presentMoreDiscover(entities: [DiscoverEntity]) {
        let viewModels = entities.map(DiscoverViewModel.init)
        viewController?.displayMoreDiscover(viewModels: viewModels)
    }
    
    func presentAlert(with message: String) {
        viewController?.displayAlert(with: message)
    }
    
}

class DiscoverViewModel{
    
    private let entity: DiscoverEntity
    
    init(entity: DiscoverEntity) {
        self.entity = entity
    }
    
    var getEntity: DiscoverEntity {
        return entity
    }
    
    var getID: Int {
        return entity.id
    }
    
    var getName: String {
        return entity.title
    }
    
    var getDescription: String {
        return entity.description
    }
    
    var status: String {
        return entity.adult == true ? "Adult only" : "All age"
    }
    
    var year: String {
        return entity.releaseDate.components(separatedBy: "-").first ?? "1928"
    }
    
    var popularity: String {
        return "★ \(entity.popularity)"
    }
    
    var imageURL: URL? {
        return URL(string: "https://image.tmdb.org/t/p/w200\(entity.poster)")
    }
}
