//
//  ReviewConfigurator.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS.
//
//

import Foundation

class ReviewConfigurator {
    
    static func inject(dependencyFor viewController: ReviewUI) {
        let router = ReviewRouter()
        let presenter = ReviewPresenter()
        
        let dataSource = ReviewRemoteDataSourceImpl()
        let repository = ReviewRepositoryImpl(datasource: dataSource)
        let usecase = GetReviewUsecase(repository: repository)

        let interactor = ReviewInteractor(getReviewUsecase: usecase)
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        
        presenter.viewController = viewController
        
        router.viewController = viewController
    }
}
