//
//  DiscoverRemoteDataSource.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

protocol DiscoverRemoteDataSource {
    
    func fetchDiscover(param: [String: Any],
                       completion: @escaping(Result<DiscoverResponse, DataError>) -> Void)

}

class DiscoverRemoteDataSourceImpl: DiscoverRemoteDataSource{

    func fetchDiscover(param: [String : Any],
                       completion: @escaping (Result<DiscoverResponse, DataError>) -> Void) {
        
        let endpoint = "/discover/movie"
        NetworkManager.shared.request(with: endpoint, withParameter: param) { (result) in
            switch result {
            case let .failure(error):
                completion(.failure(error))
            case let .success(data):
                do {
                    let json = try JSONDecoder().decode(DiscoverResponse.self, from: data)
                    completion(.success(json))
                } catch {
                    completion(.failure(.init(errorState: .parseError)))
                }
            }
        }
    }
    
}
