//
//  DiscoverUI.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation
import UIKit

protocol DiscoverDisplayLogic: BaseDisplayLogic{
    func displayDiscover(viewModel: [DiscoverViewModel])
}

class DiscoverUI: BaseViewController{
    
    //dependency
    var interactor: DiscoverInteractorLogic?
    var router: DiscoverRouterLogic?
    
    //state
    let state = DiscoverUIState()
    
    //view
    @IBOutlet weak var discoverTableView: UITableView!
    
    init() {
        super.init(nibName: nil, bundle: nil)
        DiscoverConfigurator.inject(dependencyFor: self)
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        DiscoverConfigurator.inject(dependencyFor: self)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        controllerName = "\(DiscoverUI.self)"
        title = state.titleName
    
        self.view.showAnimatedSkeleton()
        
        let param = DiscoverRequest(genreId: state.genreId, page: 1)
        interactor?.getDiscover(param: param)
    }
    
    override func setupView() {
        super.setupView()
        
        discoverTableView.isSkeletonable = true
        discoverTableView.rowHeight = UITableView.automaticDimension
//        discoverTableView.estimatedRowHeight = 250
        discoverTableView.register(DiscoverCell.nib, forCellReuseIdentifier: DiscoverCell.identifier)
    }
    
}
