//
//  ReviewRouter.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation
import UIKit

protocol ReviewRouterLogic {
    func gotoDetail(with item: ReviewEntity)
}

class ReviewRouter: ReviewRouterLogic {
    
    weak var viewController: ReviewUI?
    
    func gotoDetail(with item: ReviewEntity) {
        let destination = UIViewController()
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
}
