//
//  GenreRepositoryImpl.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

class GenreRepositoryImpl: GenreRepositoryLogic {
    
    private let datasource: GenreRemoteDataSource
    
    init(datasource: GenreRemoteDataSource) {
        self.datasource = datasource
    }
    
    func getGenre(parameter: [String : Any],
                  completion: @escaping (Result<[GenreEntity], DataError>) -> Void) {
        
        datasource.fetchGenre(param: parameter) { result in
            switch result {
            case .failure(let error):
                completion(.failure(error))
            case .success(let models):
                let entities = models
                    .map {
                        GenreEntity(id: $0.id ?? 0,
                                    name: $0.name ?? "")
                    }
                completion(.success(entities))
            }
        }
    }
}
