//
//  GenreInteractor.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates
//
//

import Foundation

protocol GenreInteractorLogic {
    func getGenre(param: GenreRequest)
}

class GenreInteractor: GenreInteractorLogic {
    
    //presenter
    var presenter: GenrePresenterLogic?
    
    //usecase
    var getGenreUsecase: GetGenreUsecase
    
    //initial
    init(getGenreUsecase: GetGenreUsecase) {
        self.getGenreUsecase = getGenreUsecase
    }
    
    //example method 
    func getGenre(param: GenreRequest) {
        
        getGenreUsecase.execute(param: param) { (result) in
            switch result {
            case .failure(let error):
                //present error to view
                self.presenter?.presentAlert(with: error.errorType.description)
                break
            case .success(let items):
                if items.count == 0 || items.isEmpty {
                    //present empty view
                }else {
                    self.presenter?.presentGenre(entities: items)
                }
                break
            }
        }
    }
    
}
