//
//  GenrePresenter.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation

protocol GenrePresenterLogic: BasePresenterLogic{
    func presentGenre(entities: [GenreEntity])
}

class GenrePresenter: GenrePresenterLogic {
    
    weak var viewController: GenreDisplayLogic?
    
    func presentGenre(entities: [GenreEntity]) {
        let viewModel = entities.map(GenreViewModel.init)
        viewController?.displayGenre(viewModel: viewModel)
    }
    
    func presentAlert(with message: String) {
        viewController?.displayAlert(with: message)
    }
}

class GenreViewModel{
    
    private let entity: GenreEntity
    
    init(entity: GenreEntity) {
        self.entity = entity
    }
    
    var getEntity: GenreEntity {
        return entity
    }
    
    var getID: Int {
        return entity.id
    }
    
    var getName: String {
        return entity.name
    }
    
}
