//
//  DetailMovieRouter.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation
import UIKit

protocol DetailMovieRouterLogic {
    func gotoDetail(with item: DetailMovieEntity)
}

class DetailMovieRouter: DetailMovieRouterLogic {
    
    weak var viewController: DetailMovieUI?
    
    func gotoDetail(with item: DetailMovieEntity) {
        let destination = UIViewController()
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
}
