//
//  DetailMovieRouter.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation
import UIKit

protocol DetailMovieRouterLogic {
    func navigateToReview(id: Int)
}

class DetailMovieRouter: DetailMovieRouterLogic {
    
    weak var viewController: DetailMovieUI?
    
    func navigateToReview(id: Int) {
        let destination = viewController?
            .storyboardInstanceWithID(name: "Main",
                                      identifier: "review_vc") as! ReviewUI
        destination.state.id = id
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
    
}
