//
//  GenreConfigurator.swift
//  TheMoviee
//
//  Created by Ilham Hadi Prabawa on 2/23/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS.
//
//

import Foundation

class GenreConfigurator {
    
    static func inject(dependencyFor viewController: GenreUI) {
        let router = GenreRouter()
        let presenter = GenrePresenter()
        
        let dataSource = GenreRemoteDataSourceImpl()
        let repository = GenreRepositoryImpl(datasource: dataSource)
        let usecase = GetGenreUsecase(repository: repository)

        let interactor = GenreInteractor(getGenreUsecase: usecase)
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        
        presenter.viewController = viewController
        
        router.viewController = viewController
    }
}
